# Gradle Properties
org.gradle.jvmargs = -Xmx2G
org.gradle.daemon = true
org.gradle.parallel = true
org.gradle.caching = true

# Mod Properties
mod_version = 1.4.1
maven_group = com.Imphuls3.createcafe
archives_base_name = createcafe

# Minecraft/Fabric Properties
minecraft_version = 1.21.1
yarn_mappings = 1.21.1+build.3
loader_version = 0.16.10
fabric_version = 0.110.5+1.21.1

# Dependencies
create_version = 0.5.1-j+mc1.21.1+fabric
registrate_version = MC1.21-1.3.0+67